name: Trivy Scan - Nginx only

on:
  push:
    branches:
      - main

jobs:
  trivy:
    runs-on: ubuntu-latest

    steps:
    - name: Install Trivy
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

    - name: Scan nginx image
      run: trivy image --exit-code 1 --severity CRITICAL,HIGH nginx:latest
