# .github/workflows/trivy-ci.yml
name: Trivy CI Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t my-nginx-image .

    - name: Install Trivy
      uses: aquasecurity/trivy-action@master

    - name: Run Trivy vulnerability scan
      run: |
        trivy image --severity CRITICAL --exit-code 1 my-nginx-image

    - name: Scan file system for secrets
      run: |
        trivy fs --scanners secret --exit-code 1 /home/ubuntu/my-project

